stages:
  - release

release:docker:
  stage: release
  image: docker:latest
  services:
    - docker:dind
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  script:
    - pwd
    - ls -alh docker
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --pull -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
